services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9092:9090
    networks:
      prom-grafana-network:
        ipv4_address: 172.35.0.200

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      prom-grafana-network:
        ipv4_address: 172.35.0.201


networks:
  prom-grafana-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/24
